### PR TITLE
add vlan counters

### PR DESCRIPTION
**Pull request by sherrieshen**
- Add support for CLI "show vlan counters"
- Add testing for vlan counters
- Updated markdown file

### CODE REVIEW

**Comment by leslie-qiwa** [comment]
@greenpau any improvement on this PR? I do need this feature to monitor vlan statistics

**Comment by greenpau** [comment]
@leslie-qiwa , it is all good. Need to find the time to merge and release

**Comment by leslie-qiwa** [comment]
Thanks for prompt reply! Maybe you can just merge, and we'll use master directly. I also found one potential bug, and may supply a patch shortly.

**Comment by greenpau** [comment]
> I also found one potential bug, and may supply a patch shortly.

@leslie-qiwa , please send it. This way I will release.

**Pull request merged**
